<?php 
/* @var $this MageProfis_NutritionInfo_Block_Nutrition */ 
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct()
?>
<?php if ($_additionalgroup = $this->getNutritionInfo()): ?>
    <h2><?php echo $this->__('Nutrition Information') ?></h2>
    <?php $i = 0; ?>
    <?php foreach ($_additionalgroup as $_additional): ?>
        <?php $i++; ?>
        <table class="data-table" id="product-attribute-specs-table-<?php echo $i ?>">
            <col width="25%" />
            <col />
            <tbody>
                <?php foreach ($_additional['items'] as $_data): ?>
                    <tr>
                        <th class="label"><?php echo $this->htmlEscape($this->__($_data['label'])) ?></th>
                        <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('product-attribute-specs-table-<?php echo $i ?>')</script>
    <?php endforeach; ?>
<?php endif; ?>